# === Notes ===
#
# Docs:
# - Query language: https://beets.readthedocs.io/en/stable/reference/query.html
# - CLI reference: https://beets.readthedocs.io/en/stable/reference/cli.html
#
# Possible bugs/improvements:
# - Wayyyy to many queries being parsed, try running `beet move` with
#   `beets.library.queries` at DEBUG.
# - Missing tracks penalty WAY too high for a singles girlie like me
# - Penalties aren't easily adjustable. Sometimes I only want it to care about
#   the track length.
# - Maybe use 'as tracks' mode if there's only one track in the directory?
# - `pylast` logs stuff

# Hey can someone explain why Apple thinks `~/Music` isn't a good music
# directory?
directory: ~/Music/Music
plugins: >-
  bandcamp
  chroma
  convert
  discogs
  duplicates
  edit
  embedart
  fetchart
  fish
  fromfilename
  info
  lastgenre
  lyrics
  spotify

verbose: true

logging:
  format: "{asctime} {name} {levelname}: {message}"
  levels:
    beets.plugins: INFO
    beets.library.queries: INFO
    musicbrainzngs.mbxml: WARNING

    urllib3: INFO
    oauthlib: INFO
    httpcore: INFO
    pylast: WARNING
    httpx: WARNING

lyrics:
  auto: true
  sources: lrclib genius tekstowo
  synced: true

import:
  move: true
  copy: false
  duplicate_action: skip
  log: ~/.cache/beets/beets.log
  languages: ['en']
  # Use metadata to partition into albums, not directory structure.
  group_albums: true

musicbrainz:
  external_ids:
    discogs: true
    spotify: true
    bandcamp: true

# Enable fingerprinting.
chroma:
    auto: true

convert:
  # Surely I will not regret this.
  delete_originals: true
  formats:
    # Use `libmp3lame` for reencoding MP3s and preserve metadata while doing so.
    #
    # See: https://stackoverflow.com/a/40313706
    # See: https://stackoverflow.com/a/52354689
    mp3: "ffmpeg -y -i $source -c:a libmp3lame -q:a 0 -map_metadata 0 -map_metadata 0:s:0 $dest"

bandcamp:
  source_weight: 0.5
  art: true
  comments_separator: "\n———\n"
  genre:
    capitalize: true
    mode: progressive # classical, progressive or psychedelic

fetchart:
  cautious: true
  sources: "itunes *"

duplicates:
  album: true # ?
  merge: true

lastgenre:
  canonical: true
  count: 5
  force: true
  min_weight: 10
  separator: '; '

spotify:
  source_weight: 0.5
