complete -c code -s d -l diff --require-parameter -d '<file> <file> Compare two files with each other.'
complete -c code -s a -l add -r -d 'Add folder(s) to the last active window.'
complete -c code -s g -l goto -r -d '<file:line[:character]> Open a file at the path on the specified line and character position.'
complete -c code -s n -l new-window -d 'Force to open a new window.'
complete -c code -s r -l reuse-window -d 'Force to open a file or folder in an already opened window.'
complete -c code -s w -l wait -d 'Wait for the files to be closed before returning.'
complete -c code -l locale -r -d '<locale> The locale to use (e.g. en-US or zh-TW).'
complete -c code -l user-data-dir -r -d '<dir> Specifies the directory that user data is kept in. Can be used to open multiple distinct instances of Code.'
complete -c code -s v -l version -d 'Print version.'
complete -c code -s h -l help -d 'Print usage.'
complete -c code -l telemetry -d 'Shows all telemetry events which VS code collects.'
complete -c code -l folder-uri -r -d '<uri> Opens a window with given folder uri(s)'
complete -c code -l file-uri -r -d '<uri> Opens a window with given file uri(s)'
complete -c code -l extensions-dir -r -d '<dir> Set the root path for extensions.'
complete -c code -l list-extensions -d 'List the installed extensions.'
complete -c code -l show-versions -d 'Show versions of installed extensions, when using --list-extension.'
complete -c code -l category -d 'Filters installed extensions by provided category, when using --list-extension.'
complete -c code -l install-extension -r -d '<extension-id | path-to-vsix> Installs or updates the extension. Use `--force` argument to avoid prompts.'
complete -c code -l uninstall-extension -r -d '<extension-id> Uninstalls an extension.'
complete -c code -l enable-proposed-api -d '<extension-id> Enables proposed API features for extensions. Can receive one or more extension IDs to enable individually.'
complete -c code -l verbose -d 'Print verbose output (implies --wait).'
complete -c code -l log -r -d "<level> Log level to use. Default is 'info'." \
    -k -a "critical error warn info debug trace off"
complete -c code -s s -l status -d 'Print process usage and diagnostics information.'
complete -c code -l prof-startup -d 'Run CPU profiler during startup'
complete -c code -l disable-extensions -d 'Disable all installed extensions.'
complete -c code -l disable-extension -r -d '<extension-id> Disable an extension.'
complete -c code -l inspect-extensions -r -d '<port> Allow debugging and profiling of extensions. Check the developer tools for the connection URI.'
complete -c code -l inspect-brk-extensions -r -d '<port> Allow debugging and profiling of extensions with the extension host being paused after start. Check the developer tools for the connection URI.'
complete -c code -l disable-gpu -d 'Disable GPU hardware acceleration.'
complete -c code -l max-memory -d 'Max memory size for a window (in Mbytes).'