user.name = "Rebecca Turner"
user.email = "rbt@sent.as"

aliases.b = ["branch"]
aliases.l = ["log", "-r", "(main..@):: | (main..@)-"]

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
