# See: https://jj-vcs.github.io/jj/latest/config/

# Default values for config items: https://github.com/jj-vcs/jj/blob/main/cli/src/config-schema.json
# Default values for templates: https://github.com/jj-vcs/jj/blob/main/cli/src/config/templates.toml

user.name = "Rebecca Turner"
user.email = "rbt@sent.as"

# keep-sorted start
aliases.blame = ["file", "annotate"]
aliases.clone = ["git", "clone"]
# `cherry-pick`.
aliases.cp = ["duplicate"]
# I keep typing this.
aliases.dup = ["duplicate"]
aliases.fetch = ["git", "fetch"]
aliases.here = ["bookmark", "set", "--revision", "@-"]
aliases.init = ["git", "init", "--colocate"]
aliases.mut = ["--ignore-immutable"]
aliases.push = ["git", "push"]
aliases.remote = ["git", "remote"]
aliases.rev-parse = ["log", "--no-graph", "--template", 'commit_id ++ "\n"', "--revisions"]
# Move all bookmarks that are ancestors of `@-` to be at `@-`.
aliases.tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
aliases.w = ["workspace"]
# keep-sorted end

# Commits starting with `private:` shouldn't be pushed.
git.private-commits = 'subject(glob:"private:*") & mine()'
# Set `--allow-new` by default.
git.push-new-bookmarks = true

# `jj` shows a log in reverse order, non-paginated. Thanks to Jana for this
# idea!
# This puts the most recent commits closest to the next shell prompt and makes
# the rest visibile in the scrollback without putting you in 'pager-mode'.
# See: https://github.com/jdonszelmann/nix-home-configs/blob/816c61985d48f367928872d50c6588ac9a87c5be/programs/jj/default.nix#L19-L23
ui.default-command = [
  "log",
  "--reversed",
  "--no-pager",
]

ui.diff-editor = ":builtin"
ui.merge-editor = "mergiraf"

# Note: Doesn't support `colorMoved`, but neither does the builtin diff formatter.
# See: https://github.com/jj-vcs/jj/issues/76
ui.pager = "delta"
ui.diff-formatter = ":git"

fsmonitor.watchman.register-snapshot-trigger = true

revset-aliases.T = "trunk()"
revset-aliases.M = "megamerge()"

revset-aliases."megamerge()" = '''
latest(
    mine()
    & mutable()
    & fork_point(trunk() | @)::
    & (
        merges()
        | subject(exact:"private: merge")
    ),
    1
)
'''

# See: https://github.com/jj-vcs/jj/discussions/6891#discussioncomment-14585371
template-aliases."first_line_suffix(description)" = """
  description
    .first_line()
    .remove_prefix(jira_issue_prefix(description))
    .lower()
    .replace(regex:"[[:^word:]]", "-")
    .replace(regex:"-+", "-")
    .replace(regex:"^-|-$", "")
"""

# Extract `[DUX-1234]` or `DUX-1234` at the start of a description into
# `DUX-1234`.
template-aliases."jira_issue_prefix(description)" = """
  description
    .match(regex:"^\\\\[?[[:upper:]]+-[[:digit:]]+\\\\]?[[:blank:]]+")
    .replace(regex:"[[:blank:]\\\\[\\\\]]+", "")
"""

# Get a named commit trailer by name from a `List<Trailer>` value.
#
# These are lines like `Closes: DUX-1234` at the end of a commit description.
template-aliases."get_trailer(trailers, key)" = """
stringify(
    coalesce(
        trailers
            .map(|trailer| if(trailer.key() == key, trailer.value()))
            .join("")
    )
)
"""

# Get a `Closes:` or `Fixes:` trailer at the end of a commit and format it for
# a branch name.
#
# E.g. `Closes: #1234` becomes `1234` and `Fixes: DUX-1234` becomes `DUX-1234`.
#
# Also, sometimes these are regular links, so anything until the last slash
# gets deleted, e.g.
#
#     Closes: https://github.com/jj-vcs/jj/issues/7749
#
# Becomes simply `7749`.
template-aliases."closes_or_fixes(trailers)" = """
stringify(
    coalesce(
        get_trailer(trailers, "Closes"),
        get_trailer(trailers, "Fixes")
    )
)
    .replace(regex:"^.*/", "")
    .replace(regex:"[[:^alnum:]&&[^_-]]", "")
"""

# When we do `jj push -c ...`, give us nice bookmarks like `wiggles/ukzu` or
# `wiggles/dux-1234/ukzu`.
#
# - If there's already a local bookmark for that commit, use that bookmark.
#   - If there's multiple, I have no clue how the bookmark that's used is
#     chosen. Once I run into that I'll probably patch this ;)
# - Otherwise, give us short bookmarks like `wiggles/ukzu`.
#   - The default is way too long, we really only need a couple characters to
#     disambiguate, especially with the prefix.
# - If the commit subject starts with a Jira-style ticket like `DUX-1234`,
#   incorporate that into the bookmark name, e.g. `wiggles/dux-1234/ukzu`.
# - If there's a `Closes:` or `Fixes:` commit trailer, incorporate that.
#   E.g. `Closes: #1234` turns into `wiggles/1234/ukzu`.
#   - Also, anything in a trailer up to the first `/` is deleted, which turns
#     URLs like `Closes: https://github.com/jj-vcs/jj/issues/7749` into
#     `wiggles/7749/ukzu`.
#
# Give us push bookmarks like `wiggles/lwls` or `wiggles/dux-1234/lwls`.
# Not sure how I feel about this.
#
# See: https://github.com/jj-vcs/jj/discussions/6891#discussioncomment-14585371
templates.git_push_bookmark = """
coalesce(
  local_bookmarks
    .map(|commit_ref| commit_ref.name()),
  truncate_end(
    244,
    separate(
      "/",
      "wiggles",
      stringify(
          coalesce(
              jira_issue_prefix(description),
              closes_or_fixes(trailers),
          )
      ).lower(),
      change_id.shortest(4)
    ),
  )
)
"""

templates.draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

# Notes:
# - There's no easy way to list/format conflicted files:
#   https://github.com/jj-vcs/jj/issues/7377
# - There's no way to write comments in templates:
#   https://github.com/jj-vcs/jj/issues/5317
templates.log = '''
builtin_log_compact
++ if(
    !description && !empty,
    diff.summary(),
)
++ if(
    conflict,
    self
        .files("all()")
        .filter(|file| file.conflict())
        .map(|file|
            label(
                "conflict",
                concat("conflict ", file.path())
            )
        )
        .join("\n")
)
'''

# Only use `watchman` in large repositories.
# This may cause issues.
#
# Multiple `$TMPDIR`s results in watchman exiting and restarting, multi-second
# pauses:
#
# > Jujutsu connects to watchman at a path based on the temporary directory prefix.
# > Only on instance of watchman can exist on a system (at least as
# > configured by jj).
# > Where there are multiple temporary directory prefixes on a system,
# > running in a shell with prefix B results in a SIGTERM to the watchman
# > launched from a shell with prefix A, etc.
# > The new watchman instance takes a few seconds to launch and crawl the
# > directories, and this delays the start of execution of the jujutsu
# > command.
#
# See: https://github.com/jj-vcs/jj/issues/5817
[[--scope]]
--when.repositories = [
    "~/mwb",
    "~/nixpkgs",
]
fsmonitor.backend = "watchman"

[[--scope]]
--when.repositories = [
    "~/mwb/prelude",
    "~/lix",
]

templates.commit_trailers = '''
if(
  !trailers.contains_key("Change-Id"),
  format_gerrit_change_id_trailer(self)
)
'''
