# See: https://jj-vcs.github.io/jj/latest/config/

user.name = "Rebecca Turner"
user.email = "rbt@sent.as"

# keep-sorted start
aliases.blame = ["file", "annotate"]
aliases.clone = ["git", "clone"]
aliases.fetch = ["git", "fetch"]
aliases.here = ["bookmark", "set", "--revision", "@-"]
aliases.init = ["git", "init", "--colocate"]
aliases.mut = ["--ignore-immutable"]
aliases.push = ["git", "push"]
# Move all bookmarks that are ancestors of `@-` to be at `@-`.
aliases.tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
# keep-sorted end

# Commits starting with `private:` shouldn't be pushed.
git.private-commits = 'subject(glob:"private:*") & mine()'

ui.default-command = "log"
ui.diff-editor = ":builtin"

# Note: Doesn't support `colorMoved`, but neither does the builtin diff formatter.
# See: https://github.com/jj-vcs/jj/issues/76
ui.pager = "delta"
ui.diff-formatter = ":git"

# TODO: Does this cause problems?
core.fsmonitor = "watchman"
core.watchman.register-snapshot-trigger = true

templates.draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
