# See: https://jj-vcs.github.io/jj/latest/config/

# Default values for config items: https://github.com/jj-vcs/jj/blob/main/cli/src/config-schema.json
# Default values for templates: https://github.com/jj-vcs/jj/blob/main/cli/src/config/templates.toml

user.name = "Rebecca Turner"
user.email = "rbt@sent.as"

# keep-sorted start
aliases.blame = ["file", "annotate"]
aliases.clone = ["git", "clone"]
# `cherry-pick`.
aliases.cp = ["duplicate"]
# I keep typing this.
aliases.dup = ["duplicate"]
aliases.fetch = ["git", "fetch"]
aliases.here = ["bookmark", "set", "--revision", "@-"]
aliases.init = ["git", "init", "--colocate"]
aliases.mut = ["--ignore-immutable"]
aliases.push = ["git", "push"]
aliases.remote = ["git", "remote"]
# Move all bookmarks that are ancestors of `@-` to be at `@-`.
aliases.tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
aliases.w = ["workspace"]
# keep-sorted end

# Commits starting with `private:` shouldn't be pushed.
git.private-commits = 'subject(glob:"private:*") & mine()'
# Set `--allow-new` by default.
git.push-new-bookmarks = true

ui.default-command = "log"
ui.diff-editor = ":builtin"

# Note: Doesn't support `colorMoved`, but neither does the builtin diff formatter.
# See: https://github.com/jj-vcs/jj/issues/76
ui.pager = "delta"
ui.diff-formatter = ":git"

fsmonitor.watchman.register-snapshot-trigger = true

templates.draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

# TODO: Add conflict information here. Needs patch upstream!
templates.log = '''
builtin_log_compact
++ if(
    !description && !empty,
    diff.summary(),
)
'''

# Only use `watchman` in large repositories.
# This may cause issues.
#
# Multiple `$TMPDIR`s results in watchman exiting and restarting, multi-second
# pauses:
#
# > Jujutsu connects to watchman at a path based on the temporary directory prefix.
# > Only on instance of watchman can exist on a system (at least as
# > configured by jj).
# > Where there are multiple temporary directory prefixes on a system,
# > running in a shell with prefix B results in a SIGTERM to the watchman
# > launched from a shell with prefix A, etc.
# > The new watchman instance takes a few seconds to launch and crawl the
# > directories, and this delays the start of execution of the jujutsu
# > command.
#
# See: https://github.com/jj-vcs/jj/issues/5817
[[--scope]]
--when.repositories = [
    "~/mwb",
    "~/nixpkgs",
]
[--scope.fsmonitor]
backend = "watchman"
