user.name = "Rebecca Turner"
user.email = "rbt@sent.as"

[aliases]
# Move all bookmarks that are ancestors of `@-` to be at `@-`.
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[ui]
default-command = "log"
diff-editor = ":builtin"

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
