imports = [
    "skins/dark-blue.hjson",
]

true_colors = true
default_flags = "h"
quit_on_last_cancel = true

[search-modes]
"<empty>" = "fuzzy path"
"/" = "regex content"

[[verbs]]
key = "ctrl-w"
internal = ":input_del_word_left"

[[verbs]]
key = "ctrl-u"
internal = ":input_clear"

[[verbs]]
key = "alt-f"
internal = ":input_go_word_right"

[[verbs]]
key = "alt-b"
internal = ":input_go_word_left"

[[verbs]]
key = "ctrl-c"
internal = ":escape"

[[verbs]]
key = "ctrl-h"
internal = ":panel_left_no_open"

[[verbs]]
key = "ctrl-l"
internal = ":panel_right"

[[verbs]]
key = "ctrl-k"
internal = ":line_up"

[[verbs]]
key = "ctrl-j"
internal = ":line_down"

[[verbs]]
shortcut = "~"
cmd = ":focus ~"

[[verbs]]
shortcut = "snew"
internal = ":sort_by_date"

[[verbs]]
invocation = "git_repo_root"
shortcut = "gr"
internal = ":focus {git-root}"

[[verbs]]
shortcut = "tc"
internal = ":toggle_counts"

[[verbs]]
shortcut = "td"
internal = ":toggle_dates"

[[verbs]]
shortcut = "tf"
internal = ":toggle_files"

[[verbs]]
shortcut = "tg"
internal = ":toggle_git_file_info"

[[verbs]]
shortcut = "tgi"
internal = ":toggle_git_ignore"

[[verbs]]
shortcut = "tgs"
internal = ":toggle_git_status"

[[verbs]]
shortcut = "th"
internal = ":toggle_hidden"

[[verbs]]
shortcut = "tp"
internal = ":toggle_perm"

[[verbs]]
shortcut = "ts"
internal = ":toggle_sizes"

[[verbs]]
shortcut = "s"
internal = ":toggle_sizes"

[[verbs]]
shortcut = "ttr"
internal = ":toggle_trim_root"

[[verbs]]
invocation = "touch {newpath}"
shortcut = "t"
external = "touch {newpath:path-from-directory}"
leave_broot = false

[[verbs]]
invocation = "ln {source} {destination}"
shortcut = "l"
external = "ln -s {destination} {source:path-from-directory}"
leave_broot = false

[[verbs]]
# key = "enter"
invocation = "nvim"
shortcut = "v"
apply_to = "file"
external = "nvim +{line} {file}"
leave_broot = true
